### ISSUE TITLE
Support multi locale environments

### ISSUE THREAD

**Issue by swernerx** [smooth-code/loadable-components#101]
I'm well aware that I've written something similar before. But I think my new case is more appropriate. I want to load a file dynamically for each view/route. At the same time I want to keep the application dynamic. The user's language is not known at tooling level. This information enters my application component as a property. The application should then load the main layout, the react-intl support in the required language and our messages file for the selected language (translations). When all three are loaded, render. The whole thing, it seems, is not problematic to implement. Unfortunately, it fails at the point where access to the variables is required. Unfortunately, these are not available in the generated code:

```js
modules: ["./Main", "./messages/" + props.language + ".json", "react-intl/locale-data/" + props.language]
```

This is what my wrapped main component looks like:

```js
const MainWrapped = loadable(async (props) => {
  const [
    { default: Main },
    { default: messages },
    { default: localeData }
  ] = await Promise.all([
    import("./Main"),
    import(`./messages/${props.language}.json`),
    import(`react-intl/locale-data/${props.language}`)
  ])

  addLocaleData(localeData)

  return (props) => (
    <IntlProvider locale={props.locale} messages={messages}>
      <Main {...props} messages={messages} />
    </IntlProvider>
  )
})
```

I'm not sure how best to solve this. Possibly with an import statement per language and file. That would be necessary inline as far as I understand you, because the import() has to be inside the function (probably because of the Babel plugin). Of course, this quickly becomes complicated/unreadable. 

Do you still think it wouldn't be a good idea to support this concept? On the webpack site you are very proud of this possibility together with chunk names, which could take up the request - the dynamic part - again.

**Comment by neoziro** [comment]
In fact the first problem is bundlers, they don't support real dynamic import. It is understandable because it is not possible to create separated chunks if you don't know what will be the chunk before. The best solution for you is to generate code (custom, Babel or Prepack) in order to be able to build it.

I close it because it is largely out of the scope of this library.

**Comment by neoziro** [comment]
@swernerx sorry I missed the last part of your message.

Currently even if it is supported by Webpack, yes it is not by Loadable Components. I think Loadable Components should be able to support it, but for that I have to re-think the way "modules" works.

I will keep it opened because it is an interesting case but keep in mind that it is not a priority and that it could never be solved.

**Comment by neoziro** [comment]
Loadable Components v3 has been released 🎉, please give a try.

👉 https://github.com/smooth-code/loadable-components
