### ISSUE TITLE
Syntax convention when using loadable

### ISSUE THREAD

**Issue by ugin** [smooth-code/loadable-components#152]
From the docs and sources I understand that the two versions work:

```js
import loadable from '@loadable/component'

const AboutUs = loadable(() => import('./AboutUs'))

const pages = {
  aboutus: loadable(() => import('./AboutUs')),
}
 ```

But the following syntax doesn't:

```jsx
<Route match="/aboutus" render={loadable(() => import('./AboutUs'))}/>
```

Its not supported or something is wrong?

**Comment by bertho-zero** [comment]
You re-create a component for each render, in my opinion you should define it outside the render.

**Comment by neoziro** [comment]
Hello @ugin, yes you are doing wrong. React Components must be created statically, `loadable` actually creates a component and as @bertho-zero said, you don't want to create in each render.

So the following syntax:

```js
<Route match="/aboutus" render={loadable(() => import('./AboutUs'))}/>
```

is a React anti-pattern.

Also, you use the `render` property instead of using the `component` property.

**Comment by ugin** [comment]
@neoziro the router is a custom solution from a project I inherited, it worked like that with a previous version of `loadable-components`, now I needed to update the deps and refactor it.

Thank you both for taking the time to answer, now it makes sense why I was going the wrong route. ❤️
