### ISSUE TITLE
Testing loadable-components with Jest snapshots

### ISSUE THREAD

**Issue by zaccolley** [smooth-code/loadable-components#201]
Hi there,

Currently to use loadable with Jest and snapshots. Is there any strategies you could see to do this, running into lots of issues and there isn't a lot of Stack Overflow on this aha!

Thanks for your help

**Comment by neoziro** [comment]
Hello @zaccolley, I have never tried to do it! Maybe you could provide some code, users should be able to help you on it.

**Comment by jhornby** [comment]
We use jest + enzyme + @loadable/components to test our code.  We just recently switched from react-loadable, and we ran into one thing that we were able to work around but could be made better.

The loadable component returns a ``` React.forwardRef ``` which in jest + enzyme tests results in seeing a <ForwardRef> as the name of the component.  This is ultimately unhelpful in ensuring regressions aren't made.  

https://reactjs.org/docs/forwarding-refs.html#displaying-a-custom-name-in-devtools talks about how to change the displayName for a ForwardRef, but this is only something that can be useful to end users if the display name includes the import path.  That puts the change in the babel camp, and while I can read through that code I am not familiar with writing babel code.

Here's an example of some of our code:

home.js
```
import loadable from "common/LoadableHOC";

const LoadableHome = loadable(() => import(/* webpackChunkName:"home" */ "./Home"));

LoadableHome.displayName = "LoadableHome";

export default LoadableHome;
```

home.spec.js
```
import React from "react";
import Home from "./index";

describe("Home", () => {

	it("renders the loadable component", () => {
		const wrapper = shallow(<div>
			<Home/>
		</div>);

		expect(wrapper).toMatchSnapshot();
	});

});
```

home.spec.js.snap
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Home renders the loadable component 1`] = `
<div>
  <LoadableHome />
</div>
`;
```

Our ``` common/LoadableHOC ``` wraps @loadable/component and breaks the forwardRef purposefully so that the displayName set in the individual file will show up in React's DevTools and in the jest snapshots.  If the babel plugin could produce another property on the object, something to the likes of:

ctor:
```
 {
  displayName: () => `Loadable(${chunkName}-${getImportArg})`
  chunkName: ...,
  isready: ...,
  requireAsync: ...,
}
```

You could then change the ``` loadable()``` code to something along:

```
...
const forwardRef = (props, ref) => (
      <EnhancedInnerLoadable forwardedRef={ref} {...props} />
);

forwardRef.displayName = ctor.displayName;

const Loadable = React.forwardRef(forwardRef);
...
```

I'd be glad to answer more questions about our jest setup if that would be helpful to anyone.

**Comment by zaccolley** [comment]
Gonna try this out, thank you @jhornby

**Comment by neoziro** [comment]
Oudated, I close it. Feel free to open a new issue.

**Comment by neoziro** [comment]
The issue is outdated I mean. The method described is not. I recommend testing library to test them. All tests in the repository use it, you can inspire from it.

**Comment by sneridagh** [comment]
@gregberge sorry, I can't see any test in this repo... can you point me to them?

**Comment by alainib** [comment]
any solution ? 
i'm trying to make it work for many hours
Thanks :)

**Comment by benedict333** [comment]
Me too trying to test loadable imports for improving the unit test coverage.  But no test is covering the import part of the code. Is there any mock option available for 'loadable' so that all the imports done via loadable can be covered as in the code?
![image](https://user-images.githubusercontent.com/45373173/116601812-82805d00-a8f0-11eb-848c-d069b812d0fb.png)

My test case code is given below;

jest.mock("loadable", () => () => ({}));

test("Should render correctly", () => {
    render(<App
    loadable={loadable}
    />);
});

**Comment by alainib** [comment]
@benedict333 
it work for you for regular loadable import with Jest ?

I cannot make it work 

exemple with this : 


```
import {NotificationsDisplay} from './components/general/NotificationsDisplay';
import {Index} from './components/routes/Index';
// this break my JEST
const {Gcu} = loadable(() => import('./components/routes/Gcu'), {fallback: <LoadingScreen /> })
```

did you add something to babel or webpack config ?

**Comment by nathanmillar16** [comment]
@benedict333 I am also trying to get coverage on the same lines that are in your screenshot. 
My snapshot tests do not cover them. Did you manage to get coverage on the loadable import lines and if so, how?
_Thanks in advance for your help_
