### ISSUE TITLE
Add a .babelrc example

### ISSUE THREAD

**Issue by eduludi** [smooth-code/loadable-components#26]
Under Readme's [Configuring Babel](https://github.com/smooth-code/loadable-components#configuring-babel) section says:

> "To have a different configuration for **_client_** and **_server_**, you can use [Babel `env` option](https://babeljs.io/docs/usage/babelrc/#env-option)."

But what I get from Babel `env` option docs is that that works for environments like `development` or `production`, and **not** for `client` or `server`. How can this can get achieved? 

Thanks!

BTW:  `loadable-components` is an **awesome** library with a good documentation!

**Comment by neoziro** [comment]
Thanks! You have an example in [smooth-code/website](https://github.com/smooth-code/website). I use [`.babelrc`](https://github.com/smooth-code/website/blob/master/.babelrc) for node and I use a specific configuration in [`webpack.config.js`](https://github.com/smooth-code/website/blob/master/webpack.config.babel.js).

Anyway, it will be easier to solve it with Babel v7 because it will accept a `.babelrc.js`. It will be make custom configuration using any environment variables.

**Comment by neoziro** [comment]
I updated readme, SSR now requires `loadable-components/babel`.
