### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by ischoe** [smooth-code/loadable-components#291]
## 💬 Questions and Help

Hi, when I try to print out the extracted scripts(getScriptTags) on the server i receive those errors in the console : Uncaught ReferenceError: exports is not defined

The code in those files starts with : 
```
exports.ids = ["components-Home"];
exports.modules = {
```

My webpack config on the server looks like this : 

```
...
module.exports = {
  devtool: isDev ? 'inline-source-map' : false,
  entry: [
    './server/index.js'
  ],
  externals: [],
  target: 'node',
  output: {
    path: path.join(__dirname, outputDirectory),
    filename: 'bundle.js',
    publicPath: '/',
  },
  mode: isDev ? 'development' : 'production',
  resolve: {
    extensions: [".js", ".jsx", ".json"]
  },
  plugins: [
    new CleanWebpackPlugin(outputDirectory),
    new LoadablePlugin(),
  ],
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        },
      },
      {
        test: /\.jsx$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              publicPath: '../'
            }
          },
          "css-loader"
        ]
      },
      {
        test: /\.(png|woff|woff2|eot|ttf|svg)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 8192,
              name: 'static/[hash]-[name].[ext]',
              publicPath: '../'
            }
          }
        ]
      }
    ]
  }
}

if(isDev) {
  module.exports.entry.push('webpack/hot/poll?1000')
  module.exports.externals.push(nodeExternals({ whitelist: ['webpack/hot/poll?1000'] }))
  module.exports.plugins.push(
    new webpack.NamedModulesPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new WebpackShellPlugin({
      onBuildStart:['echo "Webpack Start"'], 
      onBuildEnd:['node ' + path.join(__dirname, outputDirectory) + '/' + 'bundle.js']
    }),
  )
} else {
  module.exports.externals.push(nodeExternals())
}
```

Anyone knows whats going on here ?

**Comment by neoziro** [comment]
Hello @ischoe, I am sorry I don't have time to dig in this issue but I am sure someone will be able to help you! I added the badge "Help wanted".

**Comment by ischoe** [comment]
The issue was, i added @loadable/webpack-plugin on my server webpack-config file. I had to change some stuff on my webpack setup, but now it works perfektly. Thanks for this awesome plugin !

**Comment by jeroenkampinga** [comment]
Hi @ischoe I have the same issue. Can you tell me what you've changed?

**Comment by rajocular** [comment]
@ischoe I'm running into this same issue, can you share the changes you made in your Webpack config?

**Comment by akshare** [comment]
I'm experiencing the same problem.

Anyone else figure out how to solve?

**Comment by rajocular** [comment]
@akshare Do you have the loadable plugin in both server and client build? If so, then make sure you run the server build and then the client.

The reason I do it this way is because both these builds generate loadable-stats.json file and we want to use the file generated by client. Since the file name is same, it will get replaced in the output folder with the second build. 

May be there's a better way to handle the filenames here but for me this works fine for now

**Comment by akshare** [comment]
@rajocular loadable plugin (in webpack config) is only on server side (I have 2 webpack files, one for server side and one for client).

Is it supposed to be on client side as well?

I'm basically following instructions here https://loadable-components.com/docs/server-side-rendering/.
So extractor.getScriptTags() which produces the script links references the server build.

So when I load the page, preload, css and scripts all reference the server build.

My assumption was that SSR would load with server side build on page load, then when client side hydrates, it loads the client side files as needed.

Maybe I'm not understanding the basic implementation?

**Comment by rajocular** [comment]
@akshare I do not have a full understanding on this as well, the documentation is not clear enough. 

Can you add the plugin to client web pack config instead of server? I think that should work

This is my understanding, browser cannot understand the js emitted from the server side as those files are targeted for node environment. We want to serve the files generated by client

Loadable plugin is the means to find those chunks. If you run that on server config, it's gonna point to the files generated on server side which is not what we want
