### ISSUE TITLE
loadComponents null

### ISSUE THREAD

**Issue by antonybudianto** [smooth-code/loadable-components#34]
Hi, I just upgraded to 1.0.0

and I got the following error:
```sh
Uncaught TypeError: Cannot read property 'then' of null
    at Object../src/index.js (index.js:13)
    at __webpack_require__ (bootstrap 9fe4b7230cd8077e37a9:707)
    at fn (bootstrap 9fe4b7230cd8077e37a9:112)
    at Object.0 (registerServiceWorker.js:117)
    at __webpack_require__ (bootstrap 9fe4b7230cd8077e37a9:707)
    at ./node_modules/@firebase/app/dist/esm/index.js.Object.defineProperty.value (bootstrap 9fe4b7230cd8077e37a9:805)
    at bundle.js:809
```

The offending line:
```js
loadComponents().then(() => {
```

Please help, thank you

**Comment by kikoanis** [comment]
Having the same issue. I am guessing the tree traverse was not a success on server side. However, there was a change in the code that make this fail ungracefully.
I think this [line](https://github.com/smooth-code/loadable-components/blob/8076cb3f7e6147148585ab062de3a1e87d22b1e8/src/loadComponents.js#L6)
``` if (!rootState.children) return null ``` should not just return null but a promise.

I believe this is due to a change in this [line](https://github.com/smooth-code/loadable-components/blob/8076cb3f7e6147148585ab062de3a1e87d22b1e8/src/loadComponents.js#L52)

I am not entirely sure but i think that line changed from 

```var ids = window[_constants.COMPONENT_IDS] || [];```
to 
```const state = window[LOADABLE_STATE]```

notice the fallback here as ```[]```

**Comment by neoziro** [comment]
There is a problem in the promise, this is why you are getting that error. I will fix it.

**Comment by kikoanis** [comment]
Thank you for the quick fix. much appreciated.

**Comment by neoziro** [comment]
Anyway if you got this error, you should have a SSR issue. Do you have a `__LOADABLE_STATE__` in your HTML code?

**Comment by kikoanis** [comment]
I do, but it always returns an empty array.  I think because I use react-router and error boundary component. It seems that I can't get the tree traverse working correctly. Will do more digging and see if I notice anything in your code. Thanks again.

**Comment by antonybudianto** [comment]
I've __LOADABLE_STATE_ on the html, but still error
