### ISSUE TITLE
[Feature Request] On Load callback 

### ISSUE THREAD

**Issue by harryy2510** [smooth-code/loadable-components#438]
## 🚀 Feature Proposal

Is there any way I can get to know when loading is finished on parent?

## Motivation

I am using react swipeable views aith animate height. I need to update height whenever loadbale component is loaded.

**Comment by neoziro** [comment]
The way to know if a component is loading is with `fallback`. You can specify a `fallback` that notifies a context in your application. This way you can do everything you want.

Quick example:

```js
function Fallback() {
  const ctx = React.useContext(X)
  React.useEffect(() => {
    ctx.setLoading(true)
    return () => ctx.setLoading(false)
  }, [])
}

<Loadable fallback={<Fallback />} />
```

**Comment by fughur** [comment]
@gregberge 
Hello! It seems that your example would cause false trigger in cases when fallback gets unmounted before the actual loadable resolution e.g. user switching the route while loading is still in progress.
We also can't rely on the direct `.load` call for load complete indication because it will trigger `loadFn` twice if used along side with Suspense-like render wrapper.
What can we do to address such cases?

**Comment by theKashey** [comment]
> What can we do to address such cases?

You can use Suspense 😉 

> user switching the route while loading is still in progress

In this case something what will listen to "setLoading" event should be unmounted as well.

### See also
- PR adding `onLoad` callback https://github.com/gregberge/loadable-components/pull/619
