### ISSUE TITLE
[SSR/redux-saga] first F5 fetch not waited, but all the next F5 ones yes

### ISSUE THREAD

**Issue by tomtom94** [smooth-code/loadable-components#473]
My saga executed when I open a certain page in SSR server side rendering is not waited !

By which way I can wait for my saga ?

There is a [stackoverflow issue open about it](https://stackoverflow.com/questions/59146837/redux-saga-loadable-component-first-fetch-not-waited-but-all-the-next-ones-yes/59147319?noredirect=1#comment104521173_59147319)

**Comment by theKashey** [comment]
Redux saga, as well as data-fetching during SSR is something loadable component should not carry about. And could not carry about.

SSR is a single pass process, and you have to have all the data (and await for it) before rendering application. Sometimes to make it work you have to "render" you application a few times, untill it would not emit any new side effects on the next render - for example this is how graphql apollo works.

What shall you do - think how to "ask" for the data outside of React, and especially outside of React Component constructor.
Just throw `react-router` to the bin, and use `react-navi` or `react-first-router`.

Fix the root cause.
